
stages:
  - build
  - merge
  - sign

build_duo_universal:
  stage: build
  image: mcr.microsoft.com/dotnet/sdk:6.0
  script:
    - echo "Re-targeting the submodules"
    - cp .gitmodules_gitlab .gitmodules
    - git submodule sync
    - git submodule update --init --recursive
    - echo "Submodules re-targeted"
    - cd duo_universal_csharp/DuoUniversal
    - dotnet build -c Release -o ../../merge
  artifacts:
    expire_in: 5 minutes
    paths:
      - merge/DuoUniversal.dll

merge_dependencies:
  stage: merge
  needs: [build_duo_universal]
  # TODO depends on build step succeeding
  tags:
    - windows
    - adfs
  script:
    - echo "Merging the DLLs"
    - copy ThirdParty\*.dll merge\
    - cd merge
    - ..\Tools\ILMerge.exe /closed /out:DuoUniversalDeps.dll /lib:"c:\Program Files\dotnet\sdk\NuGetFallbackFolder\netstandard.library\2.0.3\build\netstandard2.0\ref" DuoUniversal.dll Microsoft.Bcl.AsyncInterfaces.dll Microsoft.CSharp.dll Microsoft.IdentityModel.JsonWebTokens.dll Microsoft.IdentityModel.Logging.dll Microsoft.IdentityModel.Tokens.dll System.Buffers.dll System.Memory.dll System.Net.Http.Json.dll System.Numerics.Vectors.dll System.Runtime.CompilerServices.Unsafe.dll System.Security.Cryptography.Cng.dll System.Text.Encodings.Web.dll System.Text.Json.dll System.Threading.Tasks.Extensions.dll
    - echo "The merging is complete"
  artifacts:
    expire_in: 30 minutes
    paths:
      - merge\DuoUniversalDeps.dll

sign_merged_dll:
  stage: sign
  needs: [merge_dependencies]
  tags:
    - windows
    - adfs
  script:
    - mkdir signed
    - copy merge\DuoUniversalDeps.dll signed\
    # where /r c:\ signtool.exe
    # TODO move to cert fingerprint if possible
    - '"c:\Program Files (x86)\Windows Kits\10\bin\x64\signtool.exe" sign /sm /n "Duo Security LLC" /i "DigiCert" /t http://timestamp.digicert.com /du www.duosecurity.com /v signed\DuoUniversalDeps.dll'
  artifacts:
    expire_in: 30 minutes
    paths:
      - signed\DuoUniversalDeps.dll

