
stages:
  - build
  - merge

build_duo_universal:
  stage: build
  image: mcr.microsoft.com/dotnet/sdk:6.0
  script:
    - echo "Re-targeting the submodules"
    - cp .gitmodules_gitlab .gitmodules
    - git submodule sync
    - git submodule update --init --recursive
    - echo "Submodules re-targeted"
    - cd duo_universal_csharp/DuoUniversal
    - dotnet build -c Release -o ../../merge
  artifacts:
    expire_in: 5 minutes
    paths:
      - merge/DuoUniversal.dll

merge_dependencies:
  stage: merge
  # TODO depends on build step succeeding
  tags:
    - apps-team
    - authproxy
  script:
    - echo "Merging the DLLs"
    - copy ThirdParty\*.dll merge\
    - cd merge
    - ..\Tools\ILMerge.exe /closed /out:DuoUniversalDeps.dll Microsoft.Bcl.AsyncInterfaces.dll Microsoft.CSharp.dll Microsoft.IdentityModel.JsonWebTokens.dll Microsoft.IdentityModel.Logging.dll Microsoft.IdentityModel.Tokens.dll System.Buffers.dll System.Memory.dll System.Net.Http.Json.dll System.Numerics.Vectors.dll System.Runtime.CompilerServices.Unsafe.dll System.Security.Cryptography.Cng.dll System.Text.Encodings.Web.dll System.Text.Json.dll System.Threading.Tasks.Extensions.dll DuoUniversal.dll
    - echo "The merging is complete"
  artifacts:
    expire_in: 30 minutes
    paths:
      - merge\DuoUniversalDeps.dll
