
stages:
  - build
  - merge

build_duo_universal:
  stage: build
  image: mcr.microsoft.com/dotnet/sdk:6.0
  script:
    - echo "Re-targeting the submodules"
    - cp .gitmodules_gitlab .gitmodules
    - git submodule sync
    - git submodule update --init --recursive
    - echo "Submodules re-targeted"
    - cd duo_universal_csharp/DuoUniversal
    - dotnet build -c Release -o ../../merge
  artifacts:
    expire_in: 5 minutes
    paths:
      - merge/DuoUniversal.dll

merge_dependencies:
  stage: merge
  # TODO depends on build step succeeding
  tags:
    - apps-team
    - authproxy
  script:
    - echo "TODO the merge for real"
    - dir merge
  # TODO artifacts
